### ISSUE TITLE
RaspberryOS 64bit and TFLite (foo.tflite)

### ISSUE THREAD

**Issue by EkkiBrue** [PINTO0309/TensorflowLite-bin#18]
### Issue Type

Others

### OS

RaspberryPi OS Stretch

### OS architecture

aarch64

### Hardware

RaspberryPi4

### Description

Im a TFLite noob. But probably someone could point me to the right direction:

I do a fresh install the following way, like described in your github:

```
sudo pip3 install numpy==1.22.3
curl -OL https://github.com/PINTO0309/TensorflowLite-bin/releases/download/v2.9.0/tflite_runtime-2.9.0-cp39-none-linux_aarch64.whl
sudo pip3 install --upgrade tflite_runtime-2.9.0-cp39-none-linux_aarch64.whl
mkdir test
curl https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp > ~/test/grace_hopper.bmp
curl https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_1.0_224_frozen.tgz | tar xzv -C ~/test mobilenet_v1_1.0_224/labels.txt
curl http://download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_1.0_224_quant.tgz | tar xzv -C ~/test
mv ~/test/mobilenet_v1_1.0_224/labels.txt ~/test/
cd test
```

After installation I try a sample:
```
python3 label_image.py --num_threads 4 --image grace_hopper.bmp --model_file mobilenet_v1_1.0_224_quant.tflite --label_file labels.txt
```
I get the following error.

```
Traceback (most recent call last):
  File "/home/pi/test/label_image.py", line 53, in <module>
    interpreter = Interpreter(
  File "/usr/local/lib/python3.9/dist-packages/tflite_runtime/interpreter.py", line 455, in __init__
    _interpreter_wrapper.CreateWrapperFromFile(
ValueError: Could not open 'foo.tflite'.
```

How do I work with foo.tflite. ? I searched the net but couldnt find any reference to this ;(
But probably I only didn't understand how this works...
 
 

### Relevant Log Output

```shell
Traceback (most recent call last):
  File "/home/pi/test/label_image.py", line 53, in <module>
    interpreter = Interpreter(
  File "/usr/local/lib/python3.9/dist-packages/tflite_runtime/interpreter.py", line 455, in __init__
    _interpreter_wrapper.CreateWrapperFromFile(
ValueError: Could not open 'foo.tflite'.
```

**Comment by PINTO0309** [comment]
"foo" is generally a synonym for "something." Replace "foo.tflite" with the "xxx.tflite" you wish to try. "foo.tflite" does not exist in this repository.

**Comment by EkkiBrue** [comment]
Thank you for such a quick response.
So I changed "foo.tflite" to "mobilenet_v1_1.0_224_quant.tflite"

an now I have laber_image.py as the following:

```
import argparse
import numpy as np
import time

from PIL import Image

from tflite_runtime.interpreter import Interpreter

def load_labels(filename):
  my_labels = []
  input_file = open(filename, 'r')
  for l in input_file:
    my_labels.append(l.strip())
  return my_labels
if __name__ == "__main__":
  floating_model = False
  parser = argparse.ArgumentParser()
  parser.add_argument(
    "-i",
    "--image",
    default="/tmp/grace_hopper.bmp", \
    help="image to be classified"
  )
  parser.add_argument(
    "-m",
    "--model_file", \
    default="/tmp/mobilenet_v1_1.0_224_quant.tflite", \
    help=".tflite model to be executed"
  )
  parser.add_argument(
    "-l",
    "--label_file",
    default="/tmp/labels.txt", \
    help="name of file containing labels"
  )
  parser.add_argument(
    "--input_mean",
    default=127.5,
    help="input_mean"
  )
  parser.add_argument(
    "--input_std",
    default=127.5, \
    help="input standard deviation"
  )
  parser.add_argument(
    "--num_threads",
    default=1,
    help="number of threads"
  )
  args = parser.parse_args()

  interpreter = Interpreter(
    model_path="mobilenet_v1_1.0_224_quant.tflite",
    num_threads=args.num_threads
  )
  try:
    interpreter.allocate_tensors()
  except:
    pass
  input_details = interpreter.get_input_details()
  output_details = interpreter.get_output_details()
  # check the type of the input tensor
  if input_details[0]['dtype'] == np.float32:
    floating_model = True
  # NxHxWxC, H:1, W:2
  height = input_details[0]['shape'][1]
  width = input_details[0]['shape'][2]
  img = Image.open(args.image)
  img = img.resize((width, height))
  # add N dim
  input_data = np.expand_dims(img, axis=0)
  if floating_model:
    input_data = (np.float32(input_data) - args.input_mean) / args.input_std

  interpreter.set_tensor(input_details[0]['index'], input_data)

  start_time = time.time()
  interpreter.invoke()
  stop_time = time.time()

  output_data = interpreter.get_tensor(output_details[0]['index'])
  results = np.squeeze(output_data)
  top_k = results.argsort()[-5:][::-1]
  labels = load_labels(args.label_file)
  for i in top_k:
    if floating_model:
      print('{0:08.6f}'.format(float(results[i]))+":", labels[i])
    else:
      print('{0:08.6f}'.format(float(results[i]/255.0))+":", labels[i])

  print("time: ", stop_time - start_time)
 ``` 
Running

 ``` 
python3 label_image.py --num_threads 4 --image grace_hopper.bmp --model_file mobilenet_v1_1.0_224_quant.tflite --label_file labels.txt
 ``` 

Now gives me

 ``` 
Traceback (most recent call last):
  File "/home/pi/test/label_image.py", line 53, in <module>
    interpreter = Interpreter(
  File "/usr/local/lib/python3.9/dist-packages/tflite_runtime/interpreter.py", line 482, in __init__
    raise ValueError('type of num_threads should be int')
ValueError: type of num_threads should be int
 ``` 
I thought I have passed the threads# via --num_threads 4 ?

Thank you very much for your effort and suport to make this run on PI easliy . I really appreciate this!

**Comment by PINTO0309** [comment]
```python
    parser.add_argument(
        "--num_threads",
        type=int,
        default=1,
        help="number of threads"
    )
```
or
```python
    interpreter = Interpreter(
        model_path=args.model_file,
        num_threads=int(args.num_threads)
    )
```

**Comment by EkkiBrue** [comment]
ok, thx. Missed that somehow. Sample working ;) Pheeww... Thank you sooo much...

```
0.698039: 653:military uniform
0.082353: 668:mortarboard
0.058824: 907:Windsor tie
0.023529: 820:stage
0.019608: 401:academic gown, academic robe, judge's robe
```

**Comment by EkkiBrue** [comment]
Probably you could add it to readme.md

https://github.com/PINTO0309/TensorflowLite-bin#readme

**Comment by PINTO0309** [comment]
You can contribute by making a pull request.
